version: '2.1'

services:
   mongo:
    image: mongo:3.4.9
    ports:
      - "27017:27017"
   app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/public/vendor
    ports:
      - "3000:3000"
    links:
      - mongo 
